<?php
namespace Tigren\Popup\Block\Popup;

class ModalPopup extends \Magento\Framework\View\Element\Template
{
    protected $_checkoutSession;

    protected $_productRepository;

    protected $_helperData;

    public function __construct(
        \Magento\Framework\View\Element\Template\Context $context,
        \Magento\Checkout\Model\Session $checkoutSession,
        \Magento\Catalog\Model\ProductRepository $productRepository,
        \Tigren\Popup\Helper\Data $helperData,
        array $data = []
    ) {
        $this->_checkoutSession = $checkoutSession;
        $this->_productRepository = $productRepository;
        $this->_helperData = $helperData;
        parent::__construct(
            $context,
            $data
        );
    }

    /**
     * @return $this
     */
    protected function _prepareLayout()
    {
        return parent::_prepareLayout();
    }
    public function getQty(){

        $qty = $this->_checkoutSession->getQuote()->getItemsCount();
        return $qty;
    }
    public function getItems()
    {
        $items = $this->_checkoutSession->getQuote()->getAllVisibleItems();
        return $items;
    }
    public function isMultipleCart()
    {
        $items = $this->getItems();

        $i = 0;
        foreach($items as $item)
        {
            if($item->getProduct()->getCustomAttribute('is_multiple_cart')) {
                if($item->getProduct()->getCustomAttribute('is_multiple_cart')->getValue() == 0) {
                    $i++;
                }
            }
        }
        return $i;
    }
    public function getBaseUrl()
    {
        return parent::getBaseUrl(); // TODO: Change the autogenerated stub
    }
    public function isModuleEnabled()
    {
        if($this->_helperData->getGeneralConfig('enable') == 1) {
            return true;
        }else {
            return false;
        }
    }
}